# select the dimension
set (dim "" CACHE STRING "dimension")
if (dim STREQUAL "")
  message(FATAL_ERROR "Please specify dimension (1,2,3) with `-D dim=<DIM>`")
endif()
if (dim STREQUAL "1")
  add_definitions(-D oneD)
elseif (dim STREQUAL "2")
  add_definitions(-D twoD)
elseif (dim STREQUAL "3")
  add_definitions(-D threeD)
else()
  message(FATAL_ERROR "Invalid dimension: pick from (1,2,3)")
endif()

# if userfile not defined
# list all files in user directory
set(user "" CACHE STRING "userfile")
set(unit "" CACHE STRING "unitfile")
if(user STREQUAL "" AND unit STREQUAL "")
  file(GLOB userfiles ${CMAKE_CURRENT_SOURCE_DIR}/../user/*.F90)
  file(GLOB unitfiles ${CMAKE_CURRENT_SOURCE_DIR}/../unit/*.F90)
  message(STATUS "Please specify userfile or unitfile with `-D user=<USERFILE>` or `-D unit=<UNITFILE>`:")
  message(STATUS "userfiles:")
  foreach(userfile ${userfiles})
    get_filename_component(userfile ${userfile} NAME)
    string(REGEX REPLACE ".F90$" "" userfile ${userfile})
    message(STATUS ": ${userfile}")
  endforeach()
  message(STATUS "unitfiles:")
  foreach(unitfile ${unitfiles})
    get_filename_component(unitfile ${unitfile} NAME)
    string(REGEX REPLACE ".F90$" "" unitfile ${unitfile})
    message(STATUS ": ${unitfile}")
  endforeach()
  message(FATAL_ERROR "userfile or unitfile not defined")
endif()
if (NOT user STREQUAL "")
  set(userfile "${CMAKE_CURRENT_SOURCE_DIR}/../user/${user}.F90")
else()
  set(userfile "${CMAKE_CURRENT_SOURCE_DIR}/../unit/${unit}.F90")
endif()

set(executable ${PROJECT_NAME}.xc)
file(GLOB_RECURSE SOURCES *.F90)
add_executable(${executable} ${SOURCES} ${userfile})
target_include_directories(${executable} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/algorithms)
target_include_directories(${executable} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/algorithms/fieldsolvers)
target_include_directories(${executable} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/algorithms/gca)
target_include_directories(${executable} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/algorithms/vay)
target_include_directories(${executable} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/algorithms/boris)
target_include_directories(${executable} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/tools)

target_link_libraries(${executable} HDF5::HDF5)
